---
version: "3.8"
services:
  linter:
    image: github/super-linter:v4
    environment:
      RUN_LOCAL: "true"
      JAVASCRIPT_DEFAULT_STYLE: prettier
      LINTER_RULES_PATH: /
      VALIDATE_ALL_CODEBASE: true
      VALIDATE_DOCKERFILE_HADOLINT: false
      # VALIDATE_CSHARP: true
      VALIDATE_EDITORCONFIG: false
      VALIDATE_GITLEAKS: false
      # VALIDATE_JAVASCRIPT_ES: true
      # VALIDATE_JAVASCRIPT_STANDARD: true
      # VALIDATE_JSON: true
      VALIDATE_MARKDOWN: false
      VALIDATE_NATURAL_LANGUAGE: false
    working_dir: /tmp/lint
    volumes:
      - ../..:/tmp/lint
