version: "3.8"
services:
  linter:
    image: github/super-linter:v4
    environment:
      RUN_LOCAL: "true"
      JAVASCRIPT_DEFAULT_STYLE: prettier
      VALIDATE_ALL_CODEBASE: true
      VALIDATE_DOCKERFILE_HADOLINT: false
      VALIDATE_EDITORCONFIG: false
      VALIDATE_GITLEAKS: false
      VALIDATE_MARKDOWN: false
      VALIDATE_NATURAL_LANGUAGE: false
    working_dir: /tmp/lint
    volumes:
      - D:\OneDrive\Documents\git\Educator:/tmp/lint
