name: Build and Deploy
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '18'
      - name: Install ADOPSE dependencies
        working-directory: ADOPSE/ClientApp
        run: npm install
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.0'
      - name: dotnet Depantancies
        working-directory: ADOPSE
        run: |
          dotnet restore
      - name: BuildTools
        working-directory: buildTool/
        run: |
          npm install
          npm install -g npm-run-all
          npm run build