---
name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ADOPSE/ClientApp
        run: npm install

      - name: Build the application
        working-directory: ADOPSE/ClientApp
        run: npm run build

      - name: Run tests
        working-directory: ADOPSE/ClientApp
        run: npm test
